# Generated by Django 2.2.5 on 2021-02-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20210213_0252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
