# Generated by Django 2.2.5 on 2021-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20210213_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.DateTimeField(),
        ),
    ]
